### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [tgambet/musicalypse-pages#1]
Hi, I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Greetings!
Nuno Jesus

**Comment by tgambet** [comment]
Hi @nunojesus,
Thanks for the offer. If you want to take a look at Musicalypse website please visit https://musicalypse.creasource.net/.
I made a temporary logo using InkScape (the big 'M' using a cursive font at the top) but I'm no designer. Your help would be most welcomed if you like the project, have ideas, and want to contribute.
Musicalypse itself is not ready yet for production but you can get an idea of what it does on the website.
Cheers,
Thomas

**Comment by nunojesus** [comment]
Hi @tgambet do you have any request? Im going to use the colors of your logo or do you want other color?

**Comment by tgambet** [comment]
Ideally I'd like two versions, one white/blue (#FAFAFA, #1E88E5) and one grey/green (#303030, #8BC34A) to match my two main themes, preferably in SVG. That's all. Feel free to suggest what you want.

**Comment by nunojesus** [comment]
Hello, I create this design for your project, see if you like it and if you want changes or other design.

Greetings

![mmmmmmmmm](https://user-images.githubusercontent.com/34600369/41497740-52f33b0c-7153-11e8-8570-b03cfc525e0b.png)

**Comment by tgambet** [comment]
Hi nunojesus,
I like it, good job! However, could the central '.|M|.' be aligned with the radius (meaning a bit lower) and be bigger? I'd like it to be more visible and the overall logo to use more space inside the round. Can you do it?
Thank you!

**Comment by nunojesus** [comment]
Hello Im make the changes that you ask me to do, see if this what you want?
![logo musicaly](https://user-images.githubusercontent.com/34600369/41499777-218f8446-717e-11e8-9bed-9a04d819d687.png)

**Comment by tgambet** [comment]
Great! Thanks for your work, that's much appreciated. If you want you can send me a pull request with your logo. I can credit you on the about page of the app and in the Readme file. I can link to your github profile or a website of yours if you want. Let me know!

**Comment by nunojesus** [comment]
What the font do you want to use?

Greetings!

Nuno Jesus

**Comment by tgambet** [comment]
I wanted to use a cursive font for my application main title and I've chosen this one: https://fonts.google.com/specimen/Cookie
(You can see it in the screenshots on Musicalypse website.) I'm open to suggestions though, nothing is decided for now.
But why do you ask for a font? I'm very happy with your logo. The SVG files of the four logos you showed me would be enough for me. However if you want to do more you're more than welcomed to suggest anything you want!

**Comment by nunojesus** [comment]
I like very much that font, I just want to know to send also the log with text.

Greetings!

Nuno

**Comment by tgambet** [comment]
No need to add the text to the logo I think, unless you make two versions, one with text and one without. It might be useful in the future though but for now I don't really need it.
Thanks a lot!

**Comment by nunojesus** [comment]
Hello I made the PR with the logo files, can you please credit me on the about page of the app and in the Readme file, you can link me github profile.
Thank you very much!
If you have other project that you need help, just say it.

**Comment by tgambet** [comment]
Thanks a lot @nunojesus !
I updated https://musicalypse.creasource.net/
I credited you in the Readme file and will do it in the application itself too.
You did a great job, I'm glad you found my project and offered your help. I'll definetly get back to you on future projects. Thanks again!

**Comment by nunojesus** [comment]
Hello Im happy that you like it, thanks for credited me.

Good luck for this project that is amazing and if you need help with something, just say it!

Greetings!

Nuno Jesus
